### ISSUE TITLE
Beijing_air_quality_report.RMD expects the resource, results folders to be inside doc folder

### ISSUE THREAD

**Issue by muntakimrafi** [UBC-MDS/beijing_air_quality_analysis#107]
Fix the code so that the RMD file can fetch data from the respective destination

**Comment by muntakimrafi** [comment]
I could not render the report when I downloaded the repo. I had to fix the folder structure to be able to create the report. 

Otherwise, the structure and the content of the report is satisfactory.

**Comment by zjr-mds** [comment]
> Fix the code so that the RMD file can fetch data from the respective destination

@muntakimrafi
Hello Abdul, does any error happen to you when you run the command 'make all'? We have tested the 'make all' command and it works to fetch the data and create the proper data folder successfully.

**Comment by muntakimrafi** [comment]
Hello, I think I made a mistake running the command in my laptop. I will get back to you guys.

**Comment by MacyChan** [comment]
#108 New issue created for update
