### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by muntakimrafi** [UBC-MDS/beijing_air_quality_analysis#108]
The following issues need to be addressed.

1. Figure 1 caption is just a sentence. Caption should describe the figure or refer to what it indicates.
2. Introduction should contain some information about why you are doing this. For example, write a few sentences about PM2.5
3. The y-axis in figure 3 is unlabeled.

Overall the report looks good.

**Comment by vtaskaev1** [comment]
Thank you, Rafi, for your feedback.

We have made modifications pertaining to each of these issues, with the below links to their respective commits:
1. [ea7f62d](https://github.com/UBC-MDS/DSCI_522_Beijing_Air_Quality/commit/ea7f62d0f39f5a146708fe9a20d8f7d1e7d6c8fd)
2. [beba649](https://github.com/UBC-MDS/DSCI_522_Beijing_Air_Quality/commit/beba649430837a03ee5d1cc4dd8a2eab44a731f5)
3. [ea8cda8](https://github.com/UBC-MDS/DSCI_522_Beijing_Air_Quality/commit/ea8cda8f61ddae6df6d0a564c8f3b35e81584315)
